ITEM_NAME_MAP = {
    "electricseed": "Electric Seed",
    "grassyseed": "Grassy Seed",
    "mistyseed": "Misty Seed",
    "psychicseed": "Psychic Seed",
    "dracoplate": "Draco Plate",
    "dragonfang": "Dragon Fang",
    "dreadplate": "Dread Plate",
    "blackglasses": "Black Glasses",
    "earthplate": "Earth Plate",
    "softsand": "Soft Sand",
    "fistplate": "Fist Plate",
    "blackbelt": "Black Belt",
    "flameplate": "Flame Plate",
    "charcoal": "Charcoal",
    "icicleplate": "Icicle Plate",
    "nevermeltice": "Never-Melt Ice",
    "insectplate": "Insect Plate",
    "silverpowder": "Silver Powder",
    "ironplate": "Iron Plate",
    "metalcoat": "Metal Coat",
    "meadowplate": "Meadow Plate",
    "roseincense": "Rose Incense",
    "miracleseed": "Miracle Seed",
    "mindplate": "Mind Plate",
    "oddincense": "Odd Incense",
    "twistedspoon": "Twisted Spoon",
    "fairyfeather": "Fairy Feather",
    "pixieplate": "Pixie Plate",
    "skyplate": "Sky Plate",
    "sharpbeak": "Sharp Beak",
    "splashplate": "Splash Plate",
    "seaincense": "Sea Incense",
    "waveincense": "Wave Incense",
    "mysticwater": "Mystic Water",
    "spookyplate": "Spooky Plate",
    "spelltag": "Spell Tag",
    "stoneplate": "Stone Plate",
    "rockincense": "Rock Incense",
    "hardstone": "Hard Stone",
    "toxicplate": "Toxic Plate",
    "poisonbarb": "Poison Barb",
    "zapplate": "Zap Plate",
    "magnet": "Magnet",
    "silkscarf": "Silk Scarf",
    "pinkbow": "Pink Bow",
    "polkadotbow": "Polkadot Bow",
    "chilanberry": "Chilan Berry",
    "occaberry": "Occa Berry",
    "passhoberry": "Passho Berry",
    "wacanberry": "Wacan Berry",
    "rindoberry": "Rindo Berry",
    "yacheberry": "Yache Berry",
    "chopleberry": "Chople Berry",
    "kebiaberry": "Kebia Berry",
    "shucaberry": "Shuca Berry",
    "cobaberry": "Coba Berry",
    "payapaberry": "Payapa Berry",
    "tangaberry": "Tanga Berry",
    "chartiberry": "Charti Berry",
    "kasibberry": "Kasib Berry",
    "habanberry": "Haban Berry",
    "colburberry": "Colbur Berry",
    "babiriberry": "Babiri Berry",
    "roseliberry": "Roseli Berry",
    "choicespecs": "Choice Specs",
    "choiceband": "Choice Band",
    "choicescarf": "Choice Scarf",
    "assaultvest": "Assault Vest",
    "focusband": "Focus Band",
    "focusash": "Focus Sash",
    "expertbelt": "Expert Belt",
    "leftovers": "Leftovers",
    "lifeorb": "Life Orb",
    "lightclay": "Light Clay",
    "razorfang": "Razor Fang",
    "rockyhelmet": "Rocky Helmet",
    "scopeLens": "Scope Lens",
    "wiseglasses": "Wise Glasses",
    "zoomlens": "Zoom Lens",
    "ejectbutton": "Eject Button",
    "heavydutyboots": "Heavy-Duty Boots",
    "mentalherb": "Mental Herb",
    "airballoon": "Air Balloon",
    "blacksludge": "Black Sludge",
    "flameorb": "Flame Orb",
    "toxicorb": "Toxic Orb",
    "muscleband": "Muscle Band",
    "whiteherb": "White Herb",
}
def normalize_item_name(poke_env_item: str) -> str | None:
    try:
        return ITEM_NAME_MAP.get(poke_env_item.lower())
    except Exception as e:
        print(f"Error normalizing item name: {e}")
        return poke_env_item
